### ISSUE TITLE
Create the Button component

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/universal-orbit-components#18]
Tasks to enhance the Button component
- [x] add tests

Tasks to make it more like existing web component
- [x] block props (see #51 )
- [ ] ~circled props~
- [x] width props (see #51 )
- [ ] ~loading props~
- [x] rename `icon` props to `iconLeft` (see #27 )
- [ ] ~animations on hover~
- [ ] ~animations on click + onBlur state~
- [x] disabled state should decrease opacity and not change it to disabled theme (see #51 )
